### ISSUE TITLE
logging in autodesk in FF doesn't trigger the fusion app to log me in.

### ISSUE THREAD

**Issue by Phizicks** [cryinkfly/Fusion-360---Linux-Wine-Version-#561]
Steve, you're awesome, been trying to fix this "reg" crash for days and your latest commit seems to have fixed it.
I now have a new problem where the login screen appears, I clicked it but no browser started. I used `wine start https://google.com` and figured it didn't start the default browser so I switched to the non snap firefox install and that fixes it.
I now login on firefox and it shows to return to the product which tries to launch with the pop up to run a call I assume to fusion but nothing happens. fusion login still says to check the browser.
I recall a workaround somewhere where to update the login session somewhere here but hoping a more elegant fix.

PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

Wine
wine-10.10 (Staging)

pulled latest `main` branch as of this post.

Used to work until the wine 10 upgrade but this latest commits gets me this far now.

let me know if I missed anything. first time posting.

**Comment by Phizicks** [comment]
oh I think I fixed it. 
```
~/.local/share/applications/adskidmgr-opener.desktop
```
I don't think this launched correctly, I just recreated it and it works now. *shrugs*
feel free to close or if you have any questions, happy to check anything you want to verify

this is my new file
```
$ cat ~/.local/share/applications/adskidmgr-opener.desktop
[Desktop Entry]
Type=Application
Name=adskidmgr Scheme Handler
Exec=env WINEPREFIX="/home/user/.autodesk_fusion/wineprefixes/default" wine "C:\\Program Files\\Autodesk\\webdeploy\\production\\12593c1ae56cc14e7d670f0d4833077eca3f3583\\Autodesk Identity Manager\\AdskIdentityManager.exe" %u
StartupNotify=false
MimeType=x-scheme-handler/adskidmgr;
```

**Comment by amjad-haider** [comment]
Hey i faced the same issue thanks for the update

**Comment by machetie** [comment]
> oh I think I fixed it.
> 
> ```
> ~/.local/share/applications/adskidmgr-opener.desktop
> ```
> 
> I don't think this launched correctly, I just recreated it and it works now. _shrugs_ feel free to close or if you have any questions, happy to check anything you want to verify
> 
> this is my new file
> 
> ```
> $ cat ~/.local/share/applications/adskidmgr-opener.desktop
> [Desktop Entry]
> Type=Application
> Name=adskidmgr Scheme Handler
> Exec=env WINEPREFIX="/home/user/.autodesk_fusion/wineprefixes/default" wine "C:\\Program Files\\Autodesk\\webdeploy\\production\\12593c1ae56cc14e7d670f0d4833077eca3f3583\\Autodesk Identity Manager\\AdskIdentityManager.exe" %u
> StartupNotify=false
> MimeType=x-scheme-handler/adskidmgr;
> ```

yep it fixed my issue loging in! thank you!

**Comment by RocketPunk** [comment]
I just did that but it doesn't seem to work on my PC. I'm on Linux Mint 22.1 (kernel 6.11.0-29), I'm getting somewhat desperate

**Comment by amschmitt** [comment]
> oh I think I fixed it.
> 
> ```
> ~/.local/share/applications/adskidmgr-opener.desktop
> ```
> 
> I don't think this launched correctly, I just recreated it and it works now. _shrugs_ feel free to close or if you have any questions, happy to check anything you want to verify
> 
> this is my new file
> 
> ```
> $ cat ~/.local/share/applications/adskidmgr-opener.desktop
> [Desktop Entry]
> Type=Application
> Name=adskidmgr Scheme Handler
> Exec=env WINEPREFIX="/home/user/.autodesk_fusion/wineprefixes/default" wine "C:\\Program Files\\Autodesk\\webdeploy\\production\\12593c1ae56cc14e7d670f0d4833077eca3f3583\\Autodesk Identity Manager\\AdskIdentityManager.exe" %u
> StartupNotify=false
> MimeType=x-scheme-handler/adskidmgr;
> ```

Same issue, fresh install of Ubuntu 24.04. If doing the above doesn't fix it for you 
- make sure you have the `apt` version of FireFox installed, not the `snap` version
- make sure there are no quotes around `%u` 🤦 
- double-check your wineprefix and the path in wine to your AdskIdentityManager.exe, mine was different than above
- disable apparmor for firefox 😬 if you get a permissions issue when the browser redirects you back to fusion (yes there's probably a better solution than this but it's late and I'm tired)

**Comment by Phizicks** [comment]
mine broke after a wine update. so back to this issue. I've now used bottles to launch it but it crashes before even starting. found it's DVDK drivers which I just disabled, tweaked some things and now got this login issue again.

the main thing I noticed is that autodesk updates change the paths to the files, have you guys been checking the long hash and file path exists?
mine is currently below but won't launch
```
Exec=env WINEPREFIX="/home/user/.var/app/com.usebottles.bottles/data/bottles/bottles/Fusion360" wine "C:\\Program Files\\Autodesk\\webdeploy\\production\\2b84ec48843dc39cc73fec4274fad44f45968ec2\\Autodesk Identity Manager\\AdskIdentityManager.exe" %u
```
